### ISSUE TITLE
How can I display those published topcis from the "t265_depth"

### ISSUE THREAD

**Issue by hzlijianjun** [tiralonghipol/t265_depth#1]
I setup and launch the t265_depth, but fail to show the topic such as "/camera/fisheye1/image_raw/rectified" in RViz. There is "Status Error" showing as following:

> Status: Error
Camera
For frame [t265_depth]: Frame [t265_depth] does not exist
Camera Info
No CameraInfo received on [/camera/fisheye1/image_raw/camera_info]. Topic may not exist.

Can you show me some light on this issue?
Thanks you and your works!
![WXWorkCapture_1619054277325](https://user-images.githubusercontent.com/1620094/115641447-b20cf380-a34b-11eb-8b6b-f3c1b9fcc370.png)

**Comment by tiralonghipol** [comment]
hi, sorry for the late reply
if you do not have transformation connecting the world frame to the t265, in Rviz you can simply set t265_depth as fixed frame

**Comment by tiralonghipol** [comment]
@hzlijianjun any update on this?

**Comment by hzlijianjun** [comment]
I'm very sorry for my coming back so late, Thanks for your response.
After some months study and expement in ROS, I have understanded a bit more. I close this comment.
