### ISSUE TITLE
For frame [t265_depth]: Frame [t265_depth] does not exist

### ISSUE THREAD

**Issue by huan-robotics** [tiralonghipol/t265_depth#2]
Hi!
Your work is great! But when I run `roslaunch t265_depth t265_depth.launch`,  everythng is OK except the error in rviz:
`For frame [t265_depth]: Frame [t265_depth] does not exist`
How can I solve it?
Thanks!

**Comment by tiralonghipol** [comment]
hei @YuHuan1021 
did you run the t265 driver before t265_depth ?
what is your fixed reference?

**Comment by huan-robotics** [comment]
> hei @YuHuan1021 did you run the t265 driver before t265_depth ? what is your fixed reference?

I run the realsense-ros package for driving T265:
`roslaunch realsense2_camera demo_t265.launch`
In rviz, the fixed frame is  **camera_odom_frame**.

**Comment by huan-robotics** [comment]
> hei @YuHuan1021 did you run the t265 driver before t265_depth ? what is your fixed reference?

Maybe I should build one **tf** between **t165_depth** to **camera_odom_frame**?

**Comment by huan-robotics** [comment]
To add a **tf**: `rosrun tf static_transform_publisher 0 0 0 0 0 camera_link t265_depth 10`, then the problem is solved. 
But the pointclouds look so bad.  Are they normal?
![t265 pointclouds problem](https://user-images.githubusercontent.com/49125918/147646678-16a37fc4-bec0-4e6b-bd7d-4c81a8d4291f.png)

**Comment by tiralonghipol** [comment]
nice!
feel free to open a pr with that line added in the lunch file

**Comment by tiralonghipol** [comment]
do not expect to use this to have a 20m map of the environment lol
it should be used for max 4/5m depending on the features you are point to
did you put you intrinsics in the yaml file?
also check your resolution

**Comment by huan-robotics** [comment]
> did you put you intrinsics in the yaml file? also check your resolution

Oh, I didn't check the yaml file. I will try. Thanks so much!

**Comment by huan-robotics** [comment]
Hi!
I have made sure the yaml file is correct, but it's still the same as the picture I commented before.  What about your show? @tiralonghipol

**Comment by tiralonghipol** [comment]
maybe this package does not fit your application? what are you trying to achieve?
to get a decent pcl with fisheye stereo block matching is very hard
the best result I ever got is summarized in this video: https://www.youtube.com/watch?v=LcsuX1bwI_8
check the top right around 0:23 and so forth

**Comment by zwy-costa** [comment]
> To add a **tf**: `rosrun tf static_transform_publisher 0 0 0 0 0 camera_link t265_depth 10`, then the problem is solved. But the pointclouds look so bad. Are they normal? ![t265 pointclouds problem](https://user-images.githubusercontent.com/49125918/147646678-16a37fc4-bec0-4e6b-bd7d-4c81a8d4291f.png)

Hi! @YuHuan1021 
I see in your image. the pointcloud seem to at the z axis
Is this correct? 
It's the same to my method
![image](https://github.com/tiralonghipol/t265_depth/assets/89819828/2c3185cf-65cc-43d4-a1c1-6c7738bd8772)

**Comment by LiuL0ngl0ng** [comment]
> > To add a **tf**: `rosrun tf static_transform_publisher 0 0 0 0 0 camera_link t265_depth 10`, then the problem is solved. But the pointclouds look so bad. Are they normal? ![t265 pointclouds problem](https://user-images.githubusercontent.com/49125918/147646678-16a37fc4-bec0-4e6b-bd7d-4c81a8d4291f.png)
> 
> Hi! @YuHuan1021 I see in your image. the pointcloud seem to at the z axis Is this correct? It's the same to my method ![image](https://user-images.githubusercontent.com/89819828/240789204-2c3185cf-65cc-43d4-a1c1-6c7738bd8772.png)

How used the package to generate the depth image?
Is it one terminal executes the command "roslaunch realsense2_camera rs_t265.launch",and another terminal executes"roslaunch t265_depth t265_depth.launch"?
then ,Do you not modify other parameter?

**Comment by huan-robotics** [comment]
> > 添加一个**tf** : `rosrun tf static_transform_publisher 0 0 0 0 0 camera_link t265_depth 10`，然后问题就解决了。但是点云看起来很糟糕。他们正常吗？![t265 点云问题](https://user-images.githubusercontent.com/49125918/147646678-16a37fc4-bec0-4e6b-bd7d-4c81a8d4291f.png)
> 
> 你好！@YuHuan1021 我看到你的形象。点云似乎在 z 轴上， 这是正确的吗？ 和我的方法一样 ![图像](https://user-images.githubusercontent.com/89819828/240789204-2c3185cf-65cc-43d4-a1c1-6c7738bd8772.png)

Sorry, I haven't continued this project for a long time and I forget how to proceed.  X﹏X

**Comment by tiralonghipol** [comment]
you need to get your intrinsics parameters using the provided realsense api as specified in the readme
being based on stereo block matching, do not expect good depth as a d455
I created this package simply to minimize weight onboard my robot and have odometry + depth from the same sensor 
a better solution would be use the d435 or d455 to get depth and use one of the camera + imu to run vio (Fei Gao's style, just to mention one)
